FROM python:3.11

WORKDIR /app

COPY requirements.txt flask_backend/ ./

RUN pip install -r ./requirements.txt

COPY flask_backend ./flask_backend

COPY models ./models
EXPOSE 5000

CMD ["python","flask_backend/main.py"]



