FROM python:3.11

WORKDIR /app

COPY requirements.txt flask_backend/ ./

RUN pip install -r ./requirements.txt

COPY flask_backend ./flask_backend

EXPOSE 5001

CMD ["python","flask_backend/api.py"]



